'use client';
import { use, useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Copy, Crown, Dice5, RotateCcw, Trophy, Users } from 'lucide-react';
import Button from '@/app/components/ui/Button';
import Card from '@/app/components/ui/Card';
import Badge from '@/app/components/ui/Badge';
import { api } from '@/app/lib/client/api';
import { playUiSound } from '@/app/lib/client/sound';

type Room={id:string;game:string;host_id:string;guest_id:string|null;status:string;state:any};
const tttLines=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
function winnerTtt(b:any[]){for(const [a,c,d] of tttLines)if(b[a]&&b[a]===b[c]&&b[a]===b[d])return b[a];return b.every(Boolean)?'draw':null}
function winnerC4(b:any[]){const ds=[[1,0],[0,1],[1,1],[1,-1]];for(let r=0;r<6;r++)for(let c=0;c<7;c++){const v=b[r*7+c];if(!v)continue;for(const[dr,dc]of ds){const q=[];for(let k=0;k<4;k++){const rr=r+dr*k,cc=c+dc*k;if(rr<0||rr>5||cc<0||cc>6)break;q.push(b[rr*7+cc])}if(q.length===4&&q.every(x=>x===v))return v}}return b.every(Boolean)?'draw':null}

export default function OnlineRoom({params}:{params:Promise<{roomId:string}>}){
  const {roomId}=use(params); const [room,setRoom]=useState<Room|null>(null); const [me,setMe]=useState(''); const [error,setError]=useState('');
  const [selected,setSelected]=useState<number|null>(null);
  const load=useCallback(async()=>{try{const m=await api<{user:{id:string}}>('/api/auth/me');setMe(m.user.id);const r=await api<{room:Room}>(`/api/games/rooms/${roomId}`);setRoom(r.room);if(r.room.guest_id===null&&r.room.host_id!==m.user.id){const j=await api<{room:Room}>('/api/games/rooms/join',{method:'POST',body:JSON.stringify({roomId})});setRoom(j.room)}}catch(e){setError(e instanceof Error?e.message:'Room unavailable');}},[roomId]);
  useEffect(()=>{void load();const t=setInterval(()=>void load(),1000);return()=>clearInterval(t)},[load]);
  const myTurn=!!room&&room.state.turn===(room.host_id===me?0:1); const mark=room?.host_id===me?'X':'O';
  const update=async(state:any)=>{if(!room||!myTurn||room.status!=='playing'||room.state.winner)return;try{const r=await api<{room:Room}>('/api/games/rooms/state',{method:'PATCH',body:JSON.stringify({roomId,state,status:'playing'})});setRoom(r.room);playUiSound(state.winner?'win':'move')}catch{playUiSound('error')}};
  const ttt=(i:number)=>{if(!room||!myTurn||room.state.board[i]||room.state.winner)return;const b=[...room.state.board];b[i]=mark;void update({board:b,turn:myTurn?1:0,winner:winnerTtt(b)})};
  const c4=(col:number)=>{if(!room||!myTurn||room.state.winner)return;const b=[...room.state.board];for(let r=5;r>=0;r--){const i=r*7+col;if(!b[i]){b[i]=mark;void update({board:b,turn:myTurn?1:0,winner:winnerC4(b)});break}}};
  const checkers=(i:number)=>{if(!room||!myTurn||room.state.winner)return;const b=[...room.state.board];if(selected===null){if(b[i]===mark){setSelected(i);return}}else{if(!b[i]&&Math.abs(Math.floor(i/8)-Math.floor(selected/8))<=2&&Math.abs(i%8-selected%8)<=2){b[i]=mark;b[selected]=null;setSelected(null);void update({board:b,turn:1-(room.host_id===me?0:1),winner:null});}else setSelected(null)}};
  const chess=(i:number)=>{if(!room||!myTurn||room.state.winner)return;const b=[...room.state.board];if(selected===null){if(b[i])setSelected(i);return}if(selected!==i){b[i]=b[selected];b[selected]='';setSelected(null);void update({board:b,turn:myTurn?1:0,winner:null})}else setSelected(null)};
  const ludo=()=>{if(!room||!myTurn)return;const dice=Math.floor(Math.random()*6)+1;const players=[...(room.state.players||[0,0,0,0])];players[room.host_id===me?0:1]=Math.min(57,players[room.host_id===me?0:1]+dice);void update({players,dice,turn:1-(room.host_id===me?0:1),winner:null})};
  const domino=()=>{if(!room||!myTurn)return;const chain=[...(room.state.chain||[])];chain.push([Math.floor(Math.random()*7),Math.floor(Math.random()*7)]);void update({chain,turn:1-(room.host_id===me?0:1),winner:chain.length>=14?'draw':null})};
  const pool=(id:number)=>{if(!room||!myTurn)return;const balls=(room.state.balls||[]).filter((b:any)=>b.id!==id);void update({balls,turn:1-(room.host_id===me?0:1),winner:balls.length===0?mark:null})};
  const copy=async()=>{await navigator.clipboard?.writeText(location.href);playUiSound('tap')};
  if(error)return <main className="min-h-screen grid place-items-center p-6"><Card variant="glass" className="p-8 text-center"><p className="text-red-400 mb-4">{error}</p><Link href="/games" className="text-cyan-400">Back to Games</Link></Card></main>;
  if(!room)return <main className="min-h-screen grid place-items-center"><div className="animate-pulse text-cyan-400">Connecting to WarHex Arena…</div></main>;
  const result=room.state.winner; const opponent=room.guest_id&&room.host_id===me?room.guest_id:room.host_id; const turnText=room.status==='waiting'?'Waiting for opponent…':result?`Match finished: ${result}`:myTurn?'Your turn':'Opponent turn';
  return <main className="min-h-screen pb-24"><header className="sticky top-0 z-30 glass-effect-strong border-b border-white/10"><div className="max-w-screen-lg mx-auto px-4 py-3 flex items-center gap-3"><Link href="/games"><Button variant="ghost" size="sm"><ArrowLeft className="w-4 h-4"/></Button></Link><div className="flex-1"><div className="flex items-center gap-2"><Crown className="w-5 h-5 text-yellow-400"/><h1 className="font-black">{room.game}</h1><Badge variant="emerald">ONLINE</Badge></div><p className="text-xs text-slate-400">{turnText}</p></div><Button variant="ghost" size="sm" onClick={copy}><Copy className="w-4 h-4"/></Button></div></header>
  <div className="max-w-xl mx-auto px-4 py-6"><div className="flex items-center justify-between mb-5"><Player label="YOU" mark={mark} active={myTurn}/><div className="text-center"><p className="text-[10px] text-slate-500">ROOM</p><p className="text-xs">{room.id.slice(0,8)}</p></div><Player label="OPPONENT" mark={mark==='X'?'O':'X'} active={!myTurn}/></div>
  <Card variant="premium" className="p-4 sm:p-6">
  {room.status==='waiting'?<div className="py-16 text-center"><Users className="w-14 h-14 mx-auto text-cyan-400 mb-4"/><h2 className="text-xl font-bold">Waiting for a real player</h2><p className="text-slate-400 mt-2 mb-6">Share this private room link, or wait for matchmaking to fill it.</p><Button variant="primary" onClick={copy}><Copy className="w-4 h-4 mr-2"/>Copy Invite</Button></div>:
  <>
  {room.game==='Tic Tac Toe'&&<div className="grid grid-cols-3 gap-2">{room.state.board.map((v:any,i:number)=><button key={i} onClick={()=>ttt(i)} className="aspect-square rounded-2xl bg-slate-950 border border-white/10 text-5xl font-black">{v&&<span className={v==='X'?'text-cyan-400':'text-fuchsia-400'}>{v}</span>}</button>)}</div>}
  {room.game==='Connect Four'&&<div className="grid grid-cols-7 gap-1.5 bg-blue-950 p-3 rounded-3xl">{room.state.board.map((v:any,i:number)=><button key={i} onClick={()=>c4(i%7)} className="aspect-square rounded-full bg-slate-950 flex items-center justify-center"><i className={`w-4/5 h-4/5 rounded-full ${v==='X'?'bg-red-500':v==='O'?'bg-yellow-400':'bg-slate-800'}`}/></button>)}</div>}
  {room.game==='Checkers'&&<div className="grid grid-cols-8 rounded-2xl overflow-hidden border-4 border-amber-950">{room.state.board.map((v:any,i:number)=><button key={i} onClick={()=>checkers(i)} className={`aspect-square flex items-center justify-center ${((Math.floor(i/8)+i)%2)?'bg-amber-900':'bg-amber-100'} ${selected===i?'ring-4 ring-inset ring-cyan-400':''}`}>{v&&<span className={`w-4/5 h-4/5 rounded-full border-2 border-black/40 ${v===mark?'bg-slate-900':'bg-white'}`}/>}</button>)}</div>}
  {room.game==='Chess'&&<div className="grid grid-cols-8 rounded-2xl overflow-hidden border-4 border-slate-950">{room.state.board.map((v:any,i:number)=><button key={i} onClick={()=>chess(i)} className={`aspect-square flex items-center justify-center text-2xl sm:text-3xl ${((Math.floor(i/8)+i)%2===0)?'bg-amber-100 text-slate-900':'bg-amber-800 text-white'} ${selected===i?'ring-4 ring-inset ring-cyan-400':''}`}>{v}</button>)}</div>}
  {room.game==='Ludo King'&&<div className="space-y-5"><div className="grid grid-cols-2 gap-2 aspect-square max-w-sm mx-auto rounded-3xl overflow-hidden border-8 border-slate-950">{['bg-red-400','bg-yellow-300','bg-blue-400','bg-emerald-400'].map((c,i)=><div key={i} className={`${c} flex items-center justify-center`}><span className="rounded-full bg-white/80 px-4 py-2 font-black text-slate-900">P{i+1}: {room.state.players?.[i]||0}</span></div>)}</div><Button variant="gold" size="lg" fullWidth disabled={!myTurn} onClick={ludo}><Dice5 className="mr-2"/>Roll {room.state.dice??'—'}</Button></div>}
  {room.game==='Domino'&&<div className="space-y-5"><div className="min-h-48 rounded-3xl bg-emerald-950 p-5 flex flex-wrap items-center justify-center gap-2">{(room.state.chain||[]).map((t:any,i:number)=><div key={i} className="w-12 h-20 rounded-xl bg-white text-slate-900 font-black grid place-items-center">{t[0]}|{t[1]}</div>)}</div><Button variant="primary" fullWidth disabled={!myTurn} onClick={domino}>Play Domino Tile</Button></div>}
  {room.game==='8 Ball Pool'&&<div className="space-y-4"><div className="rounded-[2rem] border-[10px] border-amber-900 bg-emerald-900 p-6"><div className="relative aspect-[2/1] rounded-[1.5rem] bg-emerald-700 border-4 border-emerald-950">{(room.state.balls||[]).map((b:any)=><button key={b.id} onClick={()=>pool(b.id)} style={{left:`${b.x}%`,top:`${b.y}%`}} className="absolute h-8 w-8 -translate-x-1/2 -translate-y-1/2 rounded-full bg-white text-slate-900 font-black text-xs border-2 border-slate-900">{b.id}</button>)}</div></div><p className="text-center text-xs text-slate-400">Online turn-based pool prototype — physics engine can be upgraded without changing matchmaking.</p></div>}
  {result&&<div className="mt-5 rounded-2xl bg-emerald-500/10 border border-emerald-400/20 p-4 text-center text-emerald-300 font-bold"><Trophy className="inline w-5 h-5 mr-2"/>{result==='draw'?'DRAW':`${result} WINS`}</div>}
  </>
  }
  </Card><div className="mt-5 flex justify-center"><Button variant="ghost" onClick={()=>location.reload()}><RotateCcw className="w-4 h-4 mr-2"/>Reconnect</Button></div><p className="text-center text-[11px] text-slate-600 mt-3">Opponent: {opponent?opponent.slice(0,8):'waiting'}</p></div></main>;
}
function Player({label,mark,active}:{label:string;mark:string;active:boolean}){return <div className={`rounded-2xl border px-4 py-2 ${active?'border-cyan-400/50 bg-cyan-400/10':'border-white/10 bg-white/5'}`}><p className="text-[10px] text-slate-500">{label}</p><b className="text-lg">{mark}</b></div>}
